default: &default
  adapter: <%= ENV.fetch('PEATIO_DATABASE_ADAPTER', 'mysql2') %>
  encoding: utf8
  support_json: <%= ENV.fetch('PEATIO_DATABASE_SUPPORT_JSON', 'true') %>
  collation: <%= ENV.fetch('PEATIO_DATABASE_COLLATION', 'utf8_general_ci') %>
  pool: <%= ENV.fetch("PEATIO_RAILS_MAX_THREADS", 8).to_i * ENV.fetch("WEB_CONCURRENCY", 1).to_i %>
  host: <%= ENV.fetch('PEATIO_DATABASE_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('PEATIO_DATABASE_PORT', 3306) %>
  username: <%= ENV.fetch('PEATIO_DATABASE_USER', 'root') %>
  password: <%= ENV['PEATIO_DATABASE_PASS'] %>

development:
  <<: *default
  database: peatio_development

test:
  <<: *default
  database: peatio_test

production:
  <<: *default
  database: <%= ENV.fetch('PEATIO_DATABASE_NAME', 'peatio_production') %>

archive_db:
  <<: *default
  url: <%= ENV['PEATIO_ARCHIVE_DATABASE_URL'] %>
  database: <%= ENV.fetch('PEATIO_ARCHIVE_DATABASE_NAME', 'peatio_archive_db') %>
  username: <%= ENV.fetch('PEATIO_ARCHIVE_DATABASE_USER', 'root') %>
  password: <%= ENV['PEATIO_ARCHIVE_DATABASE_PASS'] %>
  host: <%= ENV.fetch('PEATIO_ARCHIVE_DATABASE_HOST', '127.0.0.1') %>
